### PR TITLE
fix game-breaking open-legends bug

### PR DESCRIPTION
**Pull request by sv-esk**
backup world.world_data.region_details after loading
clear and restore from backup before exiting
ref https://github.com/DFHack/dfhack/issues/805

### CODE REVIEW

**Comment by lethosor** [comment]
Nice. Is region_details the only thing that gets modified when opening a legends viewscreen?

**Comment by sv-esk** [comment]
It also updates resident counts, inhabitants, cavein_flags[7] and some hf and site links(hf_site_link_home_site_realization_buildingst), (creates realizations)

**Comment by lethosor** [comment]
I'll merge this for now and add a warning until we can fix the other stuff not being restored properly.

**Comment by sharlin073** [comment]
I'm having a similar problem. Any tips to save this doomed savefile? do I have to restart?

**Pull request merged**
